clearGlobals;
global string $assNodes[];
global string $assDsos[];

global proc initAssNodeList()
{
    global string $assNodes[];
    global string $assDsos[];
    
    $assNodes = `ls -typ "aiStandIn"`;

    for($assNode in $assNodes)
    {
        $assDsos[size($assDsos)] = `getAttr ($assNode+".dso")`;
    }
    for($i=0;$i<size($assDsos);$i++)
    {
        if(size($assDsos[$i]) == 0)
        {
            $assDsos[$i] = "None";
        }
    }
}

global proc clearGlobals()
{
    global string $assNodes[];
    global string $assDsos[];
    clear $assNodes;
    clear $assDsos;
}

convertInstanceToObject;


